# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
# # TODO nf-core: Add a description of the module and list keywords
name: "cramino"
description: write your description here
keywords:
  - sort
  - example
  - genomics
tools:
  ## TODO nf-core: Add a description and other details for the software below
  - "cramino":
      description: "A tool for very fast quality assessment of long read cram/bam files."
      homepage: "None"
      documentation: "None"
      tool_dev_url: "https://github.com/wdecoster/cramino"
      doi: ""
      licence: ["MIT"]
      identifier: null

input:
  ### TODO nf-core: Add a description of all of the variables used as input
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - bam:
        type: file
        description: Sorted BAM/CRAM/ file
        pattern: "*.{bam,cram}"
        ontologies:
          - edam: "http://edamontology.org/format_2572" # BAM
          - edam: "http://edamontology.org/format_2573" # CRAM

output:
  ### TODO nf-core: Add a description of all of the variables used as output
  arrow:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.arrow":
          type: file
          description: Arrow file
          pattern: "*.{arrow}"
  txt:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.txt":
          type: file
          description: Text file containing cramino stats
          pattern: "*.{txt}"
  versions:
    - "versions.yml":
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: "http://edamontology.org/format_3750" # YAML

authors:
  - "@karlijncammel"
maintainers:
  - "@karlijncammel"
